'use client';

import React, { useState, useEffect } from 'react';
import { Users, Copy, Check, RefreshCw, Key, ShieldAlert } from 'lucide-react';

export default function TeamManagement() {
  const [loading, setLoading] = useState(true);
  const [members, setMembers] = useState<any[]>([]);
  const [inviteCode, setInviteCode] = useState<string>('');
  const [currentUserRole, setCurrentUserRole] = useState<string>('');
  const [currentUserId, setCurrentUserId] = useState<string>('');
  const [copied, setCopied] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [isRemoving, setIsRemoving] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchTeam();
  }, []);

  const handleFetchResponse = async (res: Response) => {
    if (res.status === 401) {
      window.location.href = '/login?error=session_expired';
      throw new Error('Sesión inválida');
    }
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || 'Ocurrió un error');
    return data;
  };

  const fetchTeam = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/settings/team');
      const data = await handleFetchResponse(res);
      setMembers(data.members || []);
      setInviteCode(data.inviteCode || '');
      setCurrentUserRole(data.currentUserRole || '');
      setCurrentUserId(data.currentUserId || '');
    } catch (e: any) {
      if (e.message !== 'Sesión inválida') setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(inviteCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleRegenerate = async () => {
    if (!confirm('¿Estás seguro? El código anterior dejará de funcionar inmediatamente y cualquier persona que lo intente usar no podrá entrar.')) {
      return;
    }
    
    setIsRegenerating(true);
    try {
      const res = await fetch('/api/settings/team', { method: 'PUT' });
      const data = await handleFetchResponse(res);
      setInviteCode(data.inviteCode);
    } catch (e: any) {
      if (e.message !== 'Sesión inválida') alert(e.message);
    } finally {
      setIsRegenerating(false);
    }
  };

  const handleRemoveMember = async (memberId: string, memberName: string) => {
    if (!confirm(`¿Estás seguro de que quieres expulsar a ${memberName} de la empresa? Perderá el acceso de inmediato.`)) {
      return;
    }

    setIsRemoving(memberId);
    try {
      const res = await fetch(`/api/settings/team/${memberId}`, { method: 'DELETE' });
      const data = await handleFetchResponse(res);
      // Remove from UI list
      setMembers(members.filter(m => m.id !== memberId));
      // Update invite code because it's automatically regenerated by the backend
      if (data.newInviteCode) {
        setInviteCode(data.newInviteCode);
      }
    } catch (e: any) {
      if (e.message !== 'Sesión inválida') alert(e.message);
    } finally {
      setIsRemoving(null);
    }
  };

  if (loading) {
    return <div className="p-6 text-sm text-slate-400 animate-pulse">Cargando equipo...</div>;
  }

  return (
    <div className="p-5 sm:p-6 rounded-3xl bg-slate-900 border border-slate-800 space-y-6">
      <div className="flex items-center gap-2 pb-3 border-b border-slate-800">
        <Users className="w-5 h-5 text-brand-400" />
        <h2 className="text-sm font-bold text-white">Equipo y Seguridad</h2>
      </div>

      {error && (
        <div className="p-3 rounded-xl bg-red-950/40 border border-red-900/50 text-red-400 text-xs flex items-center gap-2">
          <ShieldAlert className="w-4 h-4 flex-shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {/* Invite Code Card */}
      <div className="bg-slate-950 rounded-2xl p-5 border border-slate-800/80">
        <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3 flex items-center gap-1.5">
          <Key className="w-3.5 h-3.5" />
          Código de Invitación
        </h3>
        <p className="text-xs text-slate-500 mb-4">
          Comparte este código con tus empleados para que puedan unirse a tu empresa directamente desde la pantalla de registro.
        </p>
        
        <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center">
          <div className="flex-1 w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 flex items-center justify-between">
            <span className="font-mono text-sm text-brand-300 font-semibold tracking-wide select-all">
              {inviteCode}
            </span>
            <button 
              onClick={handleCopy}
              className="p-1.5 hover:bg-slate-800 rounded-lg transition-colors text-slate-400 hover:text-white"
              title="Copiar código"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
          <button
            onClick={handleRegenerate}
            disabled={isRegenerating || currentUserRole !== 'owner'}
            className="w-full sm:w-auto px-4 py-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold transition-colors flex items-center justify-center gap-2 disabled:opacity-50 border border-slate-700"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isRegenerating ? 'animate-spin' : ''}`} />
            Regenerar
          </button>
        </div>
      </div>

      {/* Member List */}
      <div>
        <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">Miembros Actuales ({members.length})</h3>
        <div className="space-y-2">
          {members.map((member) => (
            <div key={member.id} className="flex items-center justify-between p-3 rounded-xl bg-slate-950 border border-slate-800/50">
              <div className="flex flex-col">
                <span className="text-sm font-semibold text-white">
                  {member.name} {member.id === currentUserId && <span className="text-slate-500 text-xs font-normal ml-1">(Tú)</span>}
                </span>
                <span className="text-xs text-slate-500">{member.email}</span>
              </div>
              <div className="flex items-center gap-3">
                {member.companyRole === 'owner' ? (
                  <span className="px-2.5 py-1 rounded-full bg-amber-500/10 text-amber-400 text-[10px] font-bold uppercase border border-amber-500/20">
                    Propietario
                  </span>
                ) : (
                  <span className="px-2.5 py-1 rounded-full bg-slate-800 text-slate-300 text-[10px] font-bold uppercase border border-slate-700">
                    Miembro
                  </span>
                )}
                
                {currentUserRole === 'owner' && member.id !== currentUserId && (
                  <button
                    onClick={() => handleRemoveMember(member.id, member.name)}
                    disabled={isRemoving === member.id}
                    className="px-3 py-1 rounded-lg bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/20 text-xs font-bold uppercase transition-colors disabled:opacity-50"
                  >
                    {isRemoving === member.id ? '...' : 'Quitar'}
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
